# Generated by Django 4.2.7 on 2025-08-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['created_at']},
        ),
    ]
