# Generated by Django 4.2.7 on 2025-09-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_user_users_organiz_ca9165_idx_and_more'),
        ('accounts', '0010_update_organization_structure'),  # explicit: ensure AutoField pk before FK
        ('problems', '0003_field_problem_field_usersubjectaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='null=全体共有科目、値あり=グループ専用科目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.organization', verbose_name='所属組織'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['organization'], name='problems_su_organiz_9feb08_idx'),
        ),
    ]
