# Generated by Django 4.2.7 on 2025-10-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_subject_organization_alter_subject_name_and_more'),
    ]

    operations = [
        # SubjectGroupモデル作成
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='グループ名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL識別子')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科目グループ',
                'verbose_name_plural': '科目グループ',
                'db_table': 'problems_subject_group',
                'ordering': ['display_order', 'name'],
            },
        ),
        # Subjectモデルにgroupフィールド追加
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subjects',
                to='problems.subjectgroup',
                verbose_name='科目グループ'
            ),
        ),
    ]
