# Generated by Django 4.2.7 on 2025-10-12 06:45

from django.db import migrations


def load_initial_data(apps, schema_editor):
    SubjectGroup = apps.get_model('problems', 'SubjectGroup')
    SubjectGroup.objects.bulk_create([
        SubjectGroup(name='高校', slug='high_school', description='高校の科目', display_order=1),
        SubjectGroup(name='中学', slug='junior_high', description='中学の科目', display_order=2),
        SubjectGroup(name='小学', slug='elementary', description='小学校の科目', display_order=3),
        SubjectGroup(name='AWS資格試験', slug='aws_cert', description='AWS認定資格', display_order=4),
        SubjectGroup(name='簿記', slug='bookkeeping', description='日商簿記検定', display_order=5),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_add_subject_group_model'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
