# Generated by Django 4.2.7 on 2025-10-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_load_subject_groups'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 外部キー制約削除
            ALTER TABLE problems_subject DROP CONSTRAINT problems_subject_group_id_d4ed1b59_fk_problems_subject_group_id;

            -- 一時テーブル作成（正しいカラム順序: PK → created_at → updated_at → ...）
            CREATE TABLE problems_subject_group_new (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
              updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
              name VARCHAR(50) NOT NULL,
              slug VARCHAR(50) NOT NULL,
              description TEXT NOT NULL,
              display_order INTEGER NOT NULL,
              is_active BOOLEAN NOT NULL
            );

            -- データコピー
            INSERT INTO problems_subject_group_new
              (id, created_at, updated_at, name, slug, description, display_order, is_active)
            SELECT
              id, created_at, updated_at, name, slug, description, display_order, is_active
            FROM problems_subject_group;

            -- シーケンス調整
            SELECT setval('problems_subject_group_new_id_seq', (SELECT MAX(id) FROM problems_subject_group_new));

            -- 旧テーブル削除
            DROP TABLE problems_subject_group;

            -- リネーム
            ALTER TABLE problems_subject_group_new RENAME TO problems_subject_group;

            -- インデックス再作成
            CREATE UNIQUE INDEX problems_subject_group_slug_key ON problems_subject_group(slug);
            CREATE INDEX problems_subject_group_slug_773801fd_like ON problems_subject_group(slug varchar_pattern_ops);

            -- 外部キー制約再作成
            ALTER TABLE problems_subject
              ADD CONSTRAINT problems_subject_group_id_d4ed1b59_fk_problems_subject_group_id
              FOREIGN KEY (group_id) REFERENCES problems_subject_group(id)
              DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            -- ロールバック: 元のカラム順序でテーブル再作成
            ALTER TABLE problems_subject DROP CONSTRAINT problems_subject_group_id_d4ed1b59_fk_problems_subject_group_id;

            CREATE TABLE problems_subject_group_old (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(50) NOT NULL,
              slug VARCHAR(50) NOT NULL,
              description TEXT NOT NULL,
              display_order INTEGER NOT NULL,
              is_active BOOLEAN NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
              updated_at TIMESTAMP WITH TIME ZONE NOT NULL
            );

            INSERT INTO problems_subject_group_old
              (id, name, slug, description, display_order, is_active, created_at, updated_at)
            SELECT
              id, name, slug, description, display_order, is_active, created_at, updated_at
            FROM problems_subject_group;

            SELECT setval('problems_subject_group_old_id_seq', (SELECT MAX(id) FROM problems_subject_group_old));

            DROP TABLE problems_subject_group;
            ALTER TABLE problems_subject_group_old RENAME TO problems_subject_group;

            CREATE UNIQUE INDEX problems_subject_group_slug_key ON problems_subject_group(slug);
            CREATE INDEX problems_subject_group_slug_773801fd_like ON problems_subject_group(slug varchar_pattern_ops);

            ALTER TABLE problems_subject
              ADD CONSTRAINT problems_subject_group_id_d4ed1b59_fk_problems_subject_group_id
              FOREIGN KEY (group_id) REFERENCES problems_subject_group(id)
              DEFERRABLE INITIALLY DEFERRED;
            """
        ),
    ]
