# Generated by Django 4.2.7 on 2025-11-09 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_organization_id_to_id'),
        ('problems', '0010_consolidate_image_directory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='画像アセットの一意識別子', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_kind', models.CharField(choices=[('problem', '問題用'), ('explanation', '解説用')], default='problem', help_text='画像の用途（問題用/解説用）', max_length=20)),
                ('storage_key', models.TextField(help_text='物理ストレージのキー（例: org/1/subjects/uuid/problem/uuid.png）')),
                ('original_filename', models.TextField(blank=True, help_text='アップロード時の元ファイル名', null=True)),
                ('mime_type', models.TextField(blank=True, help_text='MIMEタイプ（例: image/png）', null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='ファイルサイズ（バイト）', null=True)),
                ('checksum_sha256', models.TextField(blank=True, help_text='SHA256ハッシュ値（整合性検証用）', null=True)),
                ('version', models.IntegerField(default=1, help_text='バージョン番号（楽観ロック用）')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='論理削除フラグ')),
            ],
            options={
                'verbose_name': '画像アセット',
                'verbose_name_plural': '画像アセット',
                'db_table': 'media_assets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='紐づけレコードの一意識別子', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_kind', models.CharField(choices=[('problem', '問題用'), ('explanation', '解説用')], help_text='画像の用途（問題用/解説用）', max_length=20)),
                ('position', models.IntegerField(help_text='表示順（1始まり）')),
            ],
            options={
                'verbose_name': '問題画像紐づけ',
                'verbose_name_plural': '問題画像紐づけ',
                'db_table': 'problem_media_assets',
                'ordering': ['problem', 'usage_kind', 'position'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='SubjectのOrganizationと一致する必要がある（データ移行中）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='explanation_image',
            field=models.CharField(blank=True, help_text='[非推奨] 旧形式。MediaAsset使用を推奨', max_length=255, null=True, verbose_name='解説画像ファイル名'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_image',
            field=models.CharField(blank=True, help_text='[非推奨] 旧形式。MediaAsset使用を推奨', max_length=255, null=True, verbose_name='問題画像ファイル名'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['id', 'organization'], name='problems_pr_id_bfe3c0_idx'),
        ),
        migrations.AddField(
            model_name='problemmediaasset',
            name='asset',
            field=models.ForeignKey(help_text='紐づく画像アセット', on_delete=django.db.models.deletion.RESTRICT, related_name='problem_links', to='problems.mediaasset'),
        ),
        migrations.AddField(
            model_name='problemmediaasset',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='組織（マルチテナント分離用・データ移行中）', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='problemmediaasset',
            name='problem',
            field=models.ForeignKey(help_text='紐づく問題', on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='画像を所有する組織（データ移行中）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='画像が紐づく科目（データ移行中）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='problems.subject'),
        ),
        migrations.AddIndex(
            model_name='problemmediaasset',
            index=models.Index(fields=['problem', 'usage_kind', 'position'], name='problem_med_problem_bd2f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='problemmediaasset',
            index=models.Index(fields=['asset'], name='problem_med_asset_i_1cc1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='problemmediaasset',
            index=models.Index(fields=['organization'], name='problem_med_organiz_2bdc38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problemmediaasset',
            unique_together={('problem', 'usage_kind', 'position'), ('problem', 'asset', 'usage_kind')},
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['id', 'organization'], name='media_asset_id_caa1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['organization', 'is_deleted'], name='media_asset_organiz_f0e2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['subject'], name='media_asset_subject_715d32_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['usage_kind'], name='media_asset_usage_k_30bab1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaasset',
            unique_together={('organization', 'storage_key')},
        ),
    ]
