# Generated by Django 4.2.7 on 2025-11-09 07:44

from django.db import migrations


def populate_problem_organization(apps, schema_editor):
    """Problem.organizationをSubject.organizationから設定"""
    Problem = apps.get_model('problems', 'Problem')
    Subject = apps.get_model('problems', 'Subject')

    # 全てのProblemについて、SubjectのOrganizationを設定
    problems_updated = 0
    for problem in Problem.objects.select_related('subject').all():
        if problem.subject and problem.subject.organization_id:
            problem.organization_id = problem.subject.organization_id
            problem.save(update_fields=['organization_id'])
            problems_updated += 1

    print(f"✅ {problems_updated}件のProblemにorganization_idを設定しました")


def reverse_populate(apps, schema_editor):
    """ロールバック処理（organization_idをNULLに戻す）"""
    Problem = apps.get_model('problems', 'Problem')
    Problem.objects.all().update(organization_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_add_media_asset_models'),
    ]

    operations = [
        migrations.RunPython(populate_problem_organization, reverse_populate),
    ]
