# Generated by Django 4.2.7 on 2025-11-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_populate_problem_organization'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='problems_su_organiz_9feb08_idx',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='field',
        ),
    ]
