# Generated by Django on 2025-01-09

from django.db import migrations, models
from django.utils.text import slugify


def populate_subject_slug(apps, schema_editor):
    """
    Subject.slugに自動生成値を設定

    ロジック:
    - 科目名からslugify（例: 「AWS認定 SAA」→「aws-saa」）
    - 同一組織内では科目名が一意のため重複チェック不要
    - 異なる組織間では同じslugでもディレクトリが分かれるため問題なし
    """
    Subject = apps.get_model('problems', 'Subject')

    updated_count = 0

    for subject in Subject.objects.all():
        # 科目名をslugify
        slug = slugify(subject.name)[:50]  # 最大50文字

        # 空の場合のフォールバック
        if not slug:
            slug = f'subject-{subject.id}'

        # 設定して保存
        subject.slug = slug
        subject.save(update_fields=['slug'])
        updated_count += 1

    print(f'✅ {updated_count}件のSubjectにslugを設定しました')


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_remove_subject_problems_su_organiz_9feb08_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.CharField(
                max_length=100,
                null=True,  # 一時的にnull許可
                blank=True,
                help_text='科目のスラッグ（ストレージパス用）'
            ),
        ),
        migrations.RunPython(
            populate_subject_slug,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(
                max_length=100,
                null=False,  # null不許可に変更
                blank=False,
                help_text='科目のスラッグ（ストレージパス用）'
            ),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['organization', 'slug'], name='problems_su_organiz_slug_idx'),
        ),
    ]
