# Generated by Django 4.2.7 on 2025-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_add_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmediaasset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='論理削除フラグ'),
        ),
    ]
