# Generated by Django 4.2.7 on 2026-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_remove_problem_points'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subject',
            name='problems_su_organiz_slug_idx',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='problem',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('single', '単一選択'), ('multiple', '複数選択')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(help_text='科目のスラッグ（ストレージパス用、例: aws-saa）', max_length=100, verbose_name='科目スラッグ'),
        ),
    ]
