# Generated by Django 4.2.7 on 2025-08-09 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_username_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(help_text='半角小文字英数字とアンダースコアのみ使用可能', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_user_id', message='ユーザーIDは半角小文字英数字とアンダースコアのみ使用できます', regex='^[a-z0-9_]+$'), django.core.validators.MinLengthValidator(3, 'ユーザーIDは3文字以上で入力してください')]),
        ),
    ]
