# Generated by Django 4.2.7 on 2025-08-09 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(help_text='半角英数字とアンダースコアのみ使用可能', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_user_id', message='ユーザーIDは半角英数字とアンダースコアのみ使用できます', regex='^[a-zA-Z0-9_]+$'), django.core.validators.MinLengthValidator(3, 'ユーザーIDは3文字以上で入力してください')]),
        ),
    ]
