# Generated by Django 4.2.7 on 2025-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_restricted_access',
            field=models.BooleanField(default=False, help_text='If True, user can only access explicitly granted subjects/fields'),
        ),
    ]
