# Generated by Django 4.2.7 on 2025-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_has_restricted_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_restricted_access',
            field=models.BooleanField(default=True, help_text='If True, user can only access explicitly granted subjects/fields'),
        ),
    ]
