# Generated by Django 4.2.7 on 2025-01-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_has_restricted_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_restricted_access',
        ),
    ]