# Generated by Django 4.2.7 on 2025-09-02 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_has_restricted_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='組織名')),
                ('code', models.SlugField(help_text='URL用の識別子（半角英数字とハイフンのみ）', unique=True, verbose_name='組織コード')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
                'db_table': 'organizations',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['code'], name='organizatio_code_c5d604_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization', verbose_name='所属組織'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='users_organiz_ca9165_idx'),
        ),
    ]
