# Generated by Django 4.2.7 on 2025-09-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_id_to_organization_id'),
    ]

    operations = [
    ]
