# Generated by Django 4.2.7 on 2025-10-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_make_organization_required'),
    ]

    operations = [
        # OrganizationCategoryモデル作成
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
                ('slug', models.SlugField(unique=True, verbose_name='URL識別子')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '組織カテゴリー',
                'verbose_name_plural': '組織カテゴリー',
                'db_table': 'organization_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        # Organizationモデルにcategoryフィールド追加
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organizations',
                to='accounts.organizationcategory',
                verbose_name='カテゴリー'
            ),
        ),
    ]
