# Generated by Django 4.2.7 on 2025-10-12 06:43

from django.db import migrations


def load_initial_data(apps, schema_editor):
    OrganizationCategory = apps.get_model('accounts', 'OrganizationCategory')
    OrganizationCategory.objects.bulk_create([
        OrganizationCategory(name='教育', slug='education', description='学習塾・予備校等', display_order=1),
        OrganizationCategory(name='資格', slug='certification', description='資格試験対策スクール', display_order=2),
        OrganizationCategory(name='ビジネス', slug='business', description='企業研修・リスキリング', display_order=3),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_organization_category_model'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
