# Generated by Django 4.2.7 on 2025-10-12 07:17

from django.db import migrations


def add_personal_category(apps, schema_editor):
    OrganizationCategory = apps.get_model('accounts', 'OrganizationCategory')
    OrganizationCategory.objects.create(
        name='個人利用',
        slug='personal',
        description='個人ユーザー',
        display_order=4
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_load_organization_categories'),
    ]

    operations = [
        migrations.RunPython(add_personal_category),
    ]
