# Generated by Django 4.2.7 on 2025-10-12 07:18

from django.db import migrations


def migrate_organization_categories(apps, schema_editor):
    # SQLを直接使用してcategory_idを設定
    # school → education, corporate → business, personal → personal
    schema_editor.execute("""
        UPDATE organizations SET category_id = (
            SELECT id FROM organization_categories WHERE slug =
                CASE
                    WHEN organizations.type = 'school' THEN 'education'
                    WHEN organizations.type = 'corporate' THEN 'business'
                    WHEN organizations.type = 'personal' THEN 'personal'
                END
        )
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_personal_category'),
    ]

    operations = [
        migrations.RunPython(migrate_organization_categories),
    ]
