# Generated by Django 4.2.7 on 2025-10-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_migrate_organization_categories'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE organizations ALTER COLUMN category_id SET NOT NULL;",
            reverse_sql="ALTER TABLE organizations ALTER COLUMN category_id DROP NOT NULL;"
        ),
    ]
