# Generated by Django 4.2.7 on 2025-10-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_set_category_not_null'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 外部キー制約削除
            ALTER TABLE organizations DROP CONSTRAINT organizations_category_id_61666075_fk_organizat;

            -- 一時テーブル作成（正しいカラム順序: PK → created_at → updated_at → ...）
            CREATE TABLE organization_categories_new (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
              updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
              name VARCHAR(50) NOT NULL,
              slug VARCHAR(50) NOT NULL,
              description TEXT NOT NULL,
              display_order INTEGER NOT NULL,
              is_active BOOLEAN NOT NULL
            );

            -- データコピー
            INSERT INTO organization_categories_new
              (id, created_at, updated_at, name, slug, description, display_order, is_active)
            SELECT
              id, created_at, updated_at, name, slug, description, display_order, is_active
            FROM organization_categories;

            -- シーケンス調整
            SELECT setval('organization_categories_new_id_seq', (SELECT MAX(id) FROM organization_categories_new));

            -- 旧テーブル削除
            DROP TABLE organization_categories;

            -- リネーム
            ALTER TABLE organization_categories_new RENAME TO organization_categories;

            -- インデックス再作成
            CREATE UNIQUE INDEX organization_categories_slug_key ON organization_categories(slug);
            CREATE INDEX organization_categories_slug_f1b6484b_like ON organization_categories(slug varchar_pattern_ops);

            -- 外部キー制約再作成
            ALTER TABLE organizations
              ADD CONSTRAINT organizations_category_id_61666075_fk_organizat
              FOREIGN KEY (category_id) REFERENCES organization_categories(id)
              DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            -- ロールバック: 元のカラム順序でテーブル再作成
            ALTER TABLE organizations DROP CONSTRAINT organizations_category_id_61666075_fk_organizat;

            CREATE TABLE organization_categories_old (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(50) NOT NULL,
              slug VARCHAR(50) NOT NULL,
              description TEXT NOT NULL,
              display_order INTEGER NOT NULL,
              is_active BOOLEAN NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
              updated_at TIMESTAMP WITH TIME ZONE NOT NULL
            );

            INSERT INTO organization_categories_old
              (id, name, slug, description, display_order, is_active, created_at, updated_at)
            SELECT
              id, name, slug, description, display_order, is_active, created_at, updated_at
            FROM organization_categories;

            SELECT setval('organization_categories_old_id_seq', (SELECT MAX(id) FROM organization_categories_old));

            DROP TABLE organization_categories;
            ALTER TABLE organization_categories_old RENAME TO organization_categories;

            CREATE UNIQUE INDEX organization_categories_slug_key ON organization_categories(slug);
            CREATE INDEX organization_categories_slug_f1b6484b_like ON organization_categories(slug varchar_pattern_ops);

            ALTER TABLE organizations
              ADD CONSTRAINT organizations_category_id_61666075_fk_organizat
              FOREIGN KEY (category_id) REFERENCES organization_categories(id)
              DEFERRABLE INITIALLY DEFERRED;
            """
        ),
    ]
