# Generated by Django 4.2.7 on 2025-11-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_reorder_organization_category_columns'),
        ('problems', '0010_consolidate_image_directory_fields'),
    ]

    operations = [
        # Step 1: 外部キー制約を一時的に削除
        migrations.RunSQL(
            sql="""
                ALTER TABLE users DROP CONSTRAINT IF EXISTS users_organization_id_fk_organizations_organization_id;
                ALTER TABLE problems_subject DROP CONSTRAINT IF EXISTS problems_subject_organization_id_fk;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: organization_id → id にリネーム（SQLで直接実行）
        migrations.RunSQL(
            sql="""
                ALTER TABLE organizations RENAME COLUMN organization_id TO id;
                ALTER SEQUENCE organizations_organization_id_seq RENAME TO organizations_id_seq;
            """,
            reverse_sql="""
                ALTER TABLE organizations RENAME COLUMN id TO organization_id;
                ALTER SEQUENCE organizations_id_seq RENAME TO organizations_organization_id_seq;
            """,
        ),

        # Step 3: problems_subject.organization_id の型を INTEGER に変換（必要な場合）
        # 理由: 新規 DB では problems.0004 が accounts.0010 より先に実行されるため
        # problems_subject.organization_id は UUID 型で作成される。
        # accounts.0010 が Organization を INTEGER PK で再作成した後、
        # problems_subject.organization_id は UUID のまま残るため型不一致が発生する。
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                  IF (
                    SELECT data_type
                    FROM information_schema.columns
                    WHERE table_name = 'problems_subject'
                      AND column_name = 'organization_id'
                  ) = 'uuid' THEN
                    ALTER TABLE problems_subject
                      ALTER COLUMN organization_id TYPE INTEGER USING NULL;
                  END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 4: 外部キー制約を再作成
        migrations.RunSQL(
            sql="""
                ALTER TABLE users
                ADD CONSTRAINT users_organization_id_fk_organizations_id
                FOREIGN KEY (organization_id) REFERENCES organizations(id) DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE problems_subject
                ADD CONSTRAINT problems_subject_organization_id_fk
                FOREIGN KEY (organization_id) REFERENCES organizations(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RemoveIndex(
            model_name='user',
            name='users_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_slug_5b8b37_idx',
            old_name='organizatio_slug_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='accounts.organizationcategory', verbose_name='カテゴリー'),
        ),
    ]
