# Generated by Django 4.2.7 on 2025-07-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacedRepetitionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5, help_text='難易度係数 (1.3以上)')),
                ('interval_days', models.IntegerField(default=1, help_text='復習間隔（日）')),
                ('repetition_count', models.IntegerField(default=0, help_text='復習回数')),
                ('next_review_date', models.DateTimeField(help_text='次回復習予定日')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='前回復習日', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_reviews', models.IntegerField(default=0, help_text='総復習回数')),
                ('correct_reviews', models.IntegerField(default=0, help_text='正解した復習回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date', '-ease_factor'],
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('problems_attempted', models.IntegerField(default=0)),
                ('problems_correct', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken in seconds')),
                ('attempt_number', models.IntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem')),
                ('study_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='studylogs.studylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('subject_difficulty', '科目別の苦手分野'), ('problem_type', '問題タイプ別の間違い'), ('time_pressure', '時間制限による間違い'), ('concept_confusion', '概念の混同'), ('calculation_error', '計算ミス'), ('reading_comprehension', '読解力不足'), ('knowledge_gap', '知識不足')], max_length=30)),
                ('problem_difficulty', models.CharField(blank=True, choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], max_length=10, null=True)),
                ('occurrence_count', models.IntegerField(default=1, help_text='このパターンが発生した回数')),
                ('total_attempts', models.IntegerField(default=1, help_text='関連問題の総試行回数')),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='間違いパターンの詳細説明')),
                ('confidence_score', models.FloatField(default=0.0, help_text='パターン認識の信頼度 (0.0-1.0)')),
                ('improvement_rate', models.FloatField(default=0.0, help_text='改善率 (0.0-1.0)')),
                ('is_active', models.BooleanField(default=True, help_text='このパターンがまだ問題となっているか')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='LearningWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(help_text='弱点のある概念名', max_length=200)),
                ('problem_count', models.IntegerField(default=0, help_text='関連問題数')),
                ('error_count', models.IntegerField(default=0, help_text='間違い数')),
                ('last_error_date', models.DateTimeField(blank=True, null=True)),
                ('improvement_score', models.FloatField(default=0.0, help_text='改善スコア (0.0-1.0)')),
                ('practice_recommendations', models.JSONField(default=list, help_text='練習推奨事項')),
                ('severity', models.CharField(choices=[('low', '軽微'), ('medium', '中程度'), ('high', '深刻'), ('critical', '重要')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_weaknesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-error_count', '-last_error_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('study_method', '学習方法の改善'), ('practice_focus', '重点練習領域'), ('time_management', '時間管理'), ('concept_review', '概念の復習'), ('foundation_building', '基礎固め'), ('advanced_practice', '応用練習'), ('exam_strategy', '試験戦略')], max_length=20)),
                ('priority', models.CharField(choices=[('urgent', '緊急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10)),
                ('title', models.CharField(help_text='提案のタイトル', max_length=200)),
                ('description', models.TextField(help_text='詳細な提案内容')),
                ('action_steps', models.JSONField(default=list, help_text='具体的なアクションステップ')),
                ('estimated_time_minutes', models.IntegerField(blank=True, help_text='推定必要時間（分）', null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '上級')], default='intermediate', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='効果評価 (1-5)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='提案の有効期限', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mistake_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='studylogs.mistakepattern')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cards', models.IntegerField(default=0)),
                ('new_cards', models.IntegerField(default=0)),
                ('due_cards', models.IntegerField(default=0)),
                ('reviewed_cards', models.IntegerField(default=0)),
                ('average_ease_factor', models.FloatField(default=0.0)),
                ('average_interval', models.FloatField(default=0.0)),
                ('retention_rate', models.FloatField(default=0.0, help_text='記憶定着率')),
                ('total_review_time', models.IntegerField(default=0, help_text='総復習時間（秒）')),
                ('average_response_time', models.FloatField(default=0.0, help_text='平均回答時間（秒）')),
                ('easy_cards_count', models.IntegerField(default=0)),
                ('medium_cards_count', models.IntegerField(default=0)),
                ('hard_cards_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStudySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_study_time', models.IntegerField(default=0, help_text='Total study time in seconds')),
                ('total_problems_attempted', models.IntegerField(default=0)),
                ('total_problems_correct', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects_studied', models.ManyToManyField(to='problems.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily_time', '毎日の学習時間'), ('daily_problems', '毎日の問題数'), ('weekly_time', '週間学習時間'), ('weekly_problems', '週間問題数'), ('accuracy', '正答率'), ('streak', '連続学習日数')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['goal_type'],
                'unique_together': {('user', 'goal_type')},
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(choices=[(0, '完全に忘れた'), (1, '間違えた（ヒントありでも困難）'), (2, '間違えた（ヒントありで思い出せた）'), (3, '正解（困難）'), (4, '正解（少し迷った）'), (5, '正解（簡単）')], help_text='学習品質スコア')),
                ('response_time_seconds', models.IntegerField(help_text='回答時間（秒）')),
                ('is_correct', models.BooleanField()),
                ('hint_used', models.BooleanField(default=False)),
                ('previous_ease_factor', models.FloatField()),
                ('previous_interval', models.IntegerField()),
                ('previous_repetition_count', models.IntegerField()),
                ('new_ease_factor', models.FloatField()),
                ('new_interval', models.IntegerField()),
                ('new_repetition_count', models.IntegerField()),
                ('next_review_date', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='studylogs.spacedrepetitioncard')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_reviews', to='problems.problem')),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studylogs.studylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['card', '-reviewed_at'], name='studylogs_s_card_id_5742ea_idx'), models.Index(fields=['user', '-reviewed_at'], name='studylogs_s_user_id_fc3d2e_idx'), models.Index(fields=['reviewed_at'], name='studylogs_s_reviewe_31e6fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='spacedrepetitioncard',
            index=models.Index(fields=['user', 'next_review_date', 'is_active'], name='studylogs_s_user_id_84ca64_idx'),
        ),
        migrations.AddIndex(
            model_name='spacedrepetitioncard',
            index=models.Index(fields=['next_review_date', 'is_active'], name='studylogs_s_next_re_deac4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spacedrepetitioncard',
            unique_together={('user', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='mistakepattern',
            unique_together={('user', 'pattern_type', 'subject', 'problem_difficulty')},
        ),
        migrations.AlterUniqueTogether(
            name='learningweakness',
            unique_together={('user', 'subject', 'concept_name')},
        ),
        migrations.AddIndex(
            model_name='learningsuggestion',
            index=models.Index(fields=['user', 'is_active', 'priority'], name='studylogs_l_user_id_fe5cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsuggestion',
            index=models.Index(fields=['user', 'is_read'], name='studylogs_l_user_id_d994b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learninganalytics',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailystudysummary',
            unique_together={('user', 'date')},
        ),
    ]
